apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      volumes:
        - name: html-config # volume name
          configMap:
            name: html-file # configmap name

      containers:
        - image: nginx
          name: nginx
          env:
            - name: country-override
              valueFrom:
                configMapKeyRef:
                  name: cellcard-config-multiple
                  key: country
          envFrom:
            - configMapRef:
                name: cellcard-config
            - configMapRef:
                name: cellcard-config-2
            - secretRef:
                name: database-creds
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html-config # volume name described in the pod

status: {}
